//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.PrintPaymentServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrintPaymentServiceReference.IPrintPaymentService")]
    public interface IPrintPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionPayOnline", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionPayOnlineResponse")]
        int TransactionPayOnline(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionPayOnline", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionPayOnlineResponse")]
        System.Threading.Tasks.Task<int> TransactionPayOnlineAsync(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionAddQuotasPrintSystem", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionAddQuotasPrintSystemResponse")]
        int TransactionAddQuotasPrintSystem(string username, int quota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionAddQuotasPrintSystem", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionAddQuotasPrintSystemResponse")]
        System.Threading.Tasks.Task<int> TransactionAddQuotasPrintSystemAsync(string username, int quota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionFaculties", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionFacultiesResponse")]
        int TransactionFaculties(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionFaculties", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionFacultiesResponse")]
        System.Threading.Tasks.Task<int> TransactionFacultiesAsync(string username, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionPointOfSale", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionPointOfSaleResponse")]
        int TransactionPointOfSale(int uid, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPrintPaymentService/TransactionPointOfSale", ReplyAction="http://tempuri.org/IPrintPaymentService/TransactionPointOfSaleResponse")]
        System.Threading.Tasks.Task<int> TransactionPointOfSaleAsync(int uid, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPrintPaymentServiceChannel : ConsoleApp.PrintPaymentServiceReference.IPrintPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrintPaymentServiceClient : System.ServiceModel.ClientBase<ConsoleApp.PrintPaymentServiceReference.IPrintPaymentService>, ConsoleApp.PrintPaymentServiceReference.IPrintPaymentService {
        
        public PrintPaymentServiceClient() {
        }
        
        public PrintPaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrintPaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintPaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrintPaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int TransactionPayOnline(string username, double amount) {
            return base.Channel.TransactionPayOnline(username, amount);
        }
        
        public System.Threading.Tasks.Task<int> TransactionPayOnlineAsync(string username, double amount) {
            return base.Channel.TransactionPayOnlineAsync(username, amount);
        }
        
        public int TransactionAddQuotasPrintSystem(string username, int quota) {
            return base.Channel.TransactionAddQuotasPrintSystem(username, quota);
        }
        
        public System.Threading.Tasks.Task<int> TransactionAddQuotasPrintSystemAsync(string username, int quota) {
            return base.Channel.TransactionAddQuotasPrintSystemAsync(username, quota);
        }
        
        public int TransactionFaculties(string username, double amount) {
            return base.Channel.TransactionFaculties(username, amount);
        }
        
        public System.Threading.Tasks.Task<int> TransactionFacultiesAsync(string username, double amount) {
            return base.Channel.TransactionFacultiesAsync(username, amount);
        }
        
        public int TransactionPointOfSale(int uid, double amount) {
            return base.Channel.TransactionPointOfSale(uid, amount);
        }
        
        public System.Threading.Tasks.Task<int> TransactionPointOfSaleAsync(int uid, double amount) {
            return base.Channel.TransactionPointOfSaleAsync(uid, amount);
        }
    }
}
